# To run: conda env create -f environment.yml
name: nerflab
channels:
    - conda-forge
    - pytorch
dependencies:
    - python=3.9
    - pip
    - pytorch=1.11
    - torchvision
    - torchaudio
    - cudatoolkit=11.3
    - numpy=1.23
    - pytorch-lightning=1.7.4
    - einops=0.4
    - matplotlib=3.5
    - opencv=4.5
    - tqdm