# To run: conda env create -f environment.yml
# To update: conda env update --file environment.yml --prune
name: nerflab
channels:
    - pytorch
    - conda-forge  # keep at the bottom
dependencies:
    - python=3.8
    - pip
    - pytorch=1.11
    - torchvision
    - torchaudio
    - cudatoolkit=11.3
    - numpy=1.23
    - pytorch-lightning=1.7.4
    - einops=0.4
    - matplotlib=3.5
    - opencv=4.5
    - imageio=2.21
    - tqdm