batch_size: 1024
chunk_size: 32768

n_coarse_samples: 64
n_fine_samples: 128

perturb: 1.
noise_std: 0.
use_disp: false

white_bkgd: false

sample_type: "coarse2fine"

include:
  - "network/paper.yaml"
  - "encoding/positional_encoding.yaml"
  - "optimizer/adam.yaml"
  - "scheduler/exponential.yaml"