include:
  - network/tcnn_hash_ff.yaml
  - encoding/tcnn_hash_grid.yaml
  - encoding/tcnn_spherical_harmonics.yaml

eps: 1e-15
betas: [0.9, 0.99]

n_coarse_samples: 512
n_fine_samples: 0

batch_size: 4096
chunk_size: -1
lrate: 1e-2
lrate_decay: 125